/**
 * Copyright 2013, 2014  by Patrick Nicolas - Scala for Machine Learning - All rights reserved
 *
 * The source code in this file is provided by the author for the sole purpose of illustrating the 
 * concepts and algorithms presented in "Scala for Machine Learning" ISBN: 978-1-783355-874-2 Packt Publishing.
 * Unless required by applicable law or agreed to in writing, software is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * 
 * Version 0.96
 */
package org.scalaml.app.chap12

import scala.collection.GenTraversableOnce
import akka.pattern.ask
import org.scalaml.app.Eval
import org.apache.log4j.Logger
import org.scalaml.core.XTSeries
import org.scalaml.scalability.akka.Partitioner
import org.scalaml.scalability.akka.message._
import akka.actor.ActorSystem
import scala.concurrent.Await
import akka.actor.Props
import scala.util.{Random, Try, Success, Failure}
import org.scalaml.scalability.akka.TransformFutures
import scala.concurrent.duration._
import akka.util.Timeout
import org.scalaml.filtering.DFT
import org.scalaml.util.Display
import java.util.concurrent.TimeoutException
import XTSeries._


		/**
		 * <p>Specialized Akka futures for the distributed discrete Fourier transform.</p>
		 * @constructor Create a set of futures for the distributed discrete Fourier transform. [xt] time series to be processed. [partitioner] Partitioning methodology for distributing time series across a cluster of worker actors.
		 * @throws IllegalArgumentException if the time series or the partitioner are not defined.
		 * 
		 * @author Patrick Nicolas
		 * @since June 5, 2014
		 * @note Scala for Machine Learning Chapter 12 Scalable frameworks/Akka
		 */
final class DFTTransformFutures(xt: DblSeries, partitioner: Partitioner)(implicit timeout: Timeout) 
				extends TransformFutures(xt, DFT[Double], partitioner)  {
  
		/**
		 * <p>Method to aggregate (reducer) the results for the discrete Fourier transform on each worker.</p>
		 * @param data array of values (vector of Double) generated by each worker actor
		 * @return Sequence of frequencies 
		 */
	override protected def aggregate(data: Array[DblSeries]): Seq[Double] = {
		require(data != null && data.size > 0, "DFTTransformFutures.aggregate Output of one of the worker is undefined")
		
		data.map(_.toArray).transpose.map(_.sum).take(10).toSeq
	}
}


object TransformFuturesEval extends Eval {
	val name: String = "TransformFuturesEval"
	private val logger = Logger.getLogger(name)
		
	private val NUM_WORKERS = 8
	private val NUM_DATA_POINTS = 1000000
	private val h = (x:Double) =>	2.0*Math.cos(Math.PI*0.005*x) +  // simulated first harmonic
							Math.cos(Math.PI*0.05*x) +   // simulated second harmonic
							0.5*Math.cos(Math.PI*0.2*x)  +    // simulated third harmonic 
							0.2*Random.nextDouble

	private val duration = Duration(10000, "millis")
	implicit val timeout = new Timeout(duration)
	implicit val actorSystem = ActorSystem("system") 

		 /** <p>Execution of the scalatest for futures design with Akka framework.
		 * This method is invoked by the  actor-based test framework function, ScalaMlTest.evaluate</p>
		 * @param args array of arguments used in the test
		 * @return -1 in case error a positive or null value if the test succeeds. 
		 */
	def run(args: Array[String]): Int = {
		Display.show(s"\n** test#${Eval.testCount} $name Data transformation futures using Akka actors", logger)
		
		val xt = XTSeries[Double](Array.tabulate(NUM_DATA_POINTS)(h(_)))
		val partitioner = new Partitioner(NUM_WORKERS)
  
		val master = actorSystem.actorOf(Props(new DFTTransformFutures(xt, partitioner)), "DFTTransform")
		Try {
			val future = master ? Start
			val result = Await.result(future, timeout.duration)
			actorSystem.shutdown
			result
		} match {
			case Success(result) => Display.show(s"TransformFuturesEval.run: ${result.toString}", logger)
			case Failure(e) => e match {
				case ex: TimeoutException => Display.show("TransformFuturesEval.run completed", logger)
				case ex: Throwable => Display.error("TransformFuturesEval.run completed", logger, e)
			}
		}
	}
}


object TransformFuturesEvalApp extends App {
	TransformFuturesEval.run(Array.empty)
}
// -----------------------------------------------  EOF ---------------------------